# resolver: nightly-2018-06-01
resolver: lts-15.8
packages:
  - '.'
extra-deps:
  - git: https://github.com/fizruk/telegram-bot-simple.git
    commit: 1855b8175bdf2bee843b75c94563f76eed73f5d5
  - servant-multipart-0.11.5@sha256:1633f715b5b53d648a1da69839bdc5046599f4f7244944d4bbf852dba38d8f4b,2319
  - cron-0.7.0 # See https://github.com/fizruk/telegram-bot-simple/issues/37 for more details
  - Spock-0.14.0.0
  - Spock-core-0.14.0.0
  - reroute-0.6.0.0
  - stm-containers-1.2
  - focus-1.0.1.4
  - stm-hamt-1.2.0.4
  - primitive-extras-0.8
  - primitive-unlifted-0.1.3.0  
  - text-time-0.3.1
  
    
ghc-options:
  "$everything": -haddock
  